#server
server:
  port: 80
  servlet:
    context-path: /
  tomcat:
    max-threads: 1000

#spring
spring:
  datasource:
    url: jdbc:mysql:///jtsys?serverTimezone=GMT
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/pages/
    suffix: .html

#mybatis
mybatis:
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations:
  - classpath:/mapper/sys/*.xml

#lOG
logging:
  level:
    com.cy: DEBUG
    
      
    
    
    
    
    
    